import { Suspense } from 'react';
import Loading from './loading';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Suspense fallback={<Loading />}>{children}</Suspense>;
}
