import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-row">
      <>
        <div
          className="bg-teal-500 w-[200px]"
          style={{ height: '100vh' }}
        >
          <ul className="text-center text-white font-semibold">
            <li>
              <Link href="/dashboard/menu">Menu</Link>
            </li>
            <li>
              <Link href="/dashboard/profile">Profile</Link>
            </li>
          </ul>
        </div>
      </>
      <div
        className="w-full
      "
      >
        {children}
      </div>
    </div>
  );
}
